### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by nalimilan** [johnmyleswhite/CategoricalData.jl#1]
As you may have read in my posts, I've picked up the work of designing a replacement for PDAs based on your package (see https://github.com/nalimilan/CategoricalData.jl, more on that soon). But I just realized there's no license attached to it. Could you add one?

**Comment by johnmyleswhite** [comment]
Done.

**Comment by nalimilan** [comment]
Thanks! That was really the #1 showstopper. :-)
